/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pkg2109106079_aldyramadhansyahputra_uas_pbo;

/**
 *
 * @author Acer
 */
public class hasilSearch extends javax.swing.JPanel {

    /**
     * Creates new form hasilSearch
     */
    public hasilSearch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelJenis = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelKategori = new javax.swing.JLabel();
        labelUkuran = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelHarga = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("UD Digi Kyokasho N-R", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("E D W I N");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 60));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setText("Nama Pakaian");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        labelNama.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        labelNama.setText("Nama Pakaian");
        add(labelNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setText("Jenis Pakaian");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        labelJenis.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        labelJenis.setText("Jenis Pakaian");
        add(labelJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel1.setText("Kategori Pakaian");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        labelKategori.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        labelKategori.setText("Kategori Pakaian");
        add(labelKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        labelUkuran.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        labelUkuran.setText("Ukuran Pakaian");
        add(labelUkuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel9.setText("Ukuran Pakaian");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        labelHarga.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        labelHarga.setText("Harga Pakaian");
        add(labelHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel11.setText("Harga Pakaian");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel labelHarga;
    public javax.swing.JLabel labelJenis;
    public javax.swing.JLabel labelKategori;
    public javax.swing.JLabel labelNama;
    public javax.swing.JLabel labelUkuran;
    // End of variables declaration//GEN-END:variables
}
